INSERT INTO functions (name) VALUES ('Vocalista)');
INSERT INTO functions (name) VALUES ('Backing');
INSERT INTO functions (name) VALUES ('Violão');
INSERT INTO functions (name) VALUES ('Guitarra');
INSERT INTO functions (name) VALUES ('Baixo');
INSERT INTO functions (name) VALUES ('Bateria');
INSERT INTO functions (name) VALUES ('Teclado');
INSERT INTO functions (name) VALUES ('Mesa de som');
INSERT INTO functions (name) VALUES ('Projeção');
INSERT INTO functions (name) VALUES ('Mídia');